language: cpp
compiler: gcc
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - export CXX="g++-4.8"
script:
  - make
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: always
